[package]
name = "fiftyonedegrees"
version = "0.1.0"
edition = "2024"

[dependencies]
strum_macros = "0.27.2"
thiserror = "2.0.16"
itertools = "0.14.0"

[build-dependencies]
bindgen = "0.72.1"
cmake = "0.1.54"

[profile.dev]
incremental = true
